// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;

public class SuiteTests : IDisposable
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public SuiteTests()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<String, Object>();
    }
    public void Dispose()
    {
        driver.Quit();
    }
    [Fact]
    public void Pruebasignout()
    {
        driver.Navigate().GoToUrl("https://www.advantageonlineshopping.com/#/");
        driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
        driver.FindElement(By.Id("menuUserSVGPath")).Click();

        Thread.Sleep(3000);
        driver.FindElement(By.Name("username")).Click();
        driver.FindElement(By.Name("username")).SendKeys("testuser159");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".ng-isolate-scope > .ng-isolate-scope:nth-child(2) label")).Click();
        driver.FindElement(By.Name("password")).SendKeys("Testuser1234");
        Thread.Sleep(3000);
        driver.FindElement(By.Id("sign_in_btnundefined")).Click();
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".containMiniTitle")).Click();
        Assert.Equal(driver.FindElement(By.CssSelector(".roboto-medium:nth-child(3)")).Text, "Sign out");
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".roboto-medium:nth-child(3)")).Click();
        Thread.Sleep(3000);
        driver.Close();
    }
}
